#!/bin/busybox sh

## video=mxcepdcfb:E60,bpp=8

echo "== Booting Fread =="

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

# Experimental fat32 automount
#
/sbin/losetup -o 8192 /dev/loop/0 /dev/mmcblk0p4
/bin/mkdir -p /mnt/us
/bin/mount -t vfat -o defaults,noatime,utf8,noexec,shortname=mixed /dev/loop/0 /mnt/us

# Experimental fread rootfs automount
/sbin/losetup /dev/loop/1 /mnt/us/freadfs2.ext4
/bin/mkdir -p /mnt/fread
/bin/mount -t ext4       -o defaults,noatime /dev/loop/1 /mnt/fread

# Experimental fread pivot and change root
#/bin/mkdir -p /mnt/fread/initrd
#cd /mnt/fread
#/sbin/pivot_root . initrd

# pivot_root not working so using this for now
/bin/umount /proc
/bin/umount /sys
chroot /mnt/fread
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

# initialize graphics
modprobe eink_fb_waveform
modprobe eink_fb_hal
modprobe mxc_epdc_fb dont_register_fb=1
modprobe eink_fb_hal_fslepdc bootstrap=0

# start X
X -config /etc/X.fbdev.conf &

# or try:
X -config /etc/Xorg.conf -logfile /tmp/Xorg.log -modulepath /lib/xorg/mod
ules &


# problems and solutions

* https://lists.debian.org/debian-arm/2009/02/msg00065.html
* http://www.mail-archive.com/xorg@lists.freedesktop.org/msg04115.html


exec /bin/sh
