#!/bin/busybox sh

## video=mxcepdcfb:E60,bpp=8

echo "== Booting Fread =="

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

# Experimental fat32 automount
#
/sbin/losetup -o 8192 /dev/loop/0 /dev/mmcblk0p4
/bin/mkdir -p /mnt/us
/bin/mount -t vfat -o defaults,noatime,utf8,noexec,shortname=mixed /dev/loop/0 /mnt/us

# Experimental fread rootfs automount
/sbin/losetup /dev/loop/1 /mnt/us/freadfs.ext2
/bin/mkdir -p /mnt/fread
/bin/mount -t ext2 -o defaults,noatime /dev/loop/1 /mnt/fread

# Experimental fread pivot and change root
#/bin/mkdir -p /mnt/fread/initrd
#cd /mnt/fread
#/sbin/pivot_root . initrd

# pivot_root not working so using this for now
/bin/umount /proc
/bin/umount /sys
chroot /mnt/fread
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys

# start X
modprobe mxc_epdc_fb
X -config /etc/X.conf

exec /bin/sh
